name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # frontend 폴더 안에서 빌드 실행 (리포지토리 구조 기준)
      - name: Install and Build Frontend
        run: |
          npm install
          REACT_APP_BACKEND_URL=http://${{ secrets.HOST }}:3001 npm run build
        working-directory: ./frontend

      # 빌드된 파일을 서버의 임시 폴더로 복사
      - name: Copy build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/build/"
          target: "/tmp" 

      # 서버에 접속해서 실제 배포 작업 실행
      - name: Update and Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 백엔드 업데이트 (서버의 실제 경로 사용)
            cd ${{ secrets.BACKEND_DIR }}
            git pull origin main
            pm2 restart cer-backend

            # 프론트엔드 업데이트 (서버의 실제 경로 사용)
            sudo rm -rf ${{ secrets.FRONTEND_DIR }}/*
            sudo mv /tmp/build/* ${{ secrets.FRONTEND_DIR }}/